  parameters:
  - name: rmkey
    displayName: backendAzureRmKey
    type: string
    default: 'terraform.tfstate'
    values:
    - backup.tfstate
    - terraform.tfstate
  trigger: none
  steps: 
  - template: terraformCI-template-step.yml
