  parameters:
  - name: rmkey
    displayName: backendAzureRmKey
    type: string
    default: 'terraform.tfstate'
    values:
    - backup.tfstate
  trigger: none
  steps: 
  - template: terraformCI-template-step.yml
    parameters: 
      rmkey: ${{ parameters.rmkey }}
