  parameters:
  - name: serviceARM
    displayName: backendServiceArm
    type: string
    default: new  
  - name: group_name
    displayName: backendAzureRmResourceGroupName
    type: string
    default: packer-resources
  - name: acc_name
    displayName: backendAzureRmStorageAccountName
    type: string
    default: packerstorage16
  - name: container_name
    displayName: backendAzureRmContainerName
    type: string
    default: packer-container   
  - name: rmkey
    displayName: backendAzureRmKey
    type: string
    default: terraform.tfstate
  - name: service
    displayName: environmentServiceNameAzureRM
    type: string
    default: c70fbfa3-77ff-4651-ab13-05b836eef3f7
    
    
    



  trigger: none
  steps: 
  - template: terraformCI-template-step.yml
    parameters: 
      serviceARM: ${{ parameters.serviceARM }}
      rmkey: ${{ parameters.rmkey }}
      service: ${{ parameters.service }}
      container_name: ${{ parameters.container_name }}
      acc_name: ${{ parameters.acc_name }}
      group_name: ${{ parameters.group_name }}
 
      
