  parameters:
  - name: rmkey
    displayName: backendAzureRmKey
    type: string
    default: terraform.tfstate
  - name: service
    displayName: environmentServiceNameAzureRM
    type: string
    default: Free Trial(5ff7175a-050e-4ea4-b68a-1561ca20211b)
  - name: container_name
    displayName: backendAzureRmContainerName
    type: string
    default: terraform
  - name: acc_name
    displayName: backendAzureRmStorageAccountName
    type: string
    default: terra139
  - name: group_name
    displayName: backendAzureRmResourceGroupName
    type: string
    default: ot-test
  - name: serviceARM
    displayName: backendServiceArm
    type: string
    default: ot-microservices 
   
  trigger: none
  steps: 
  - template: terraformCI-template-step.yml
    parameters: 
      rmkey: ${{ parameters.rmkey }}
      service: ${{ parameters.service }}
      container_name: ${{ parameters.container_name }}
      acc_name: ${{ parameters.acc_name }}
      group_name: ${{ parameters.group_name }}
      serviceARM: ${{ parameters.serviceARM }}
