  parameters:
  - name: rmkey
    displayName: backendAzureRmKey
    type: string
   
  trigger: none
  steps: 
  - template: terraformCI-template-step.yml
    parameters: 
      rmkey: ${{ parameters.rmkey }}
